# Generated by Django 5.2.17 on 2026-09-22 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField()),
                ('category', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('outcome', models.CharField(max_length=50, null=True)),
                ('actor_role', models.CharField(max_length=20, null=True)),
                ('target_type', models.CharField(max_length=100, null=True)),
                ('target_id', models.BigIntegerField(null=True)),
                ('source_ip', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('actor_role__isnull', True), ('actor_role__in', ['STUDENT', 'TEACHER', 'ADMIN']), _connector='OR'), name='auditlog_auditevent_actor_role_valid'), models.CheckConstraint(condition=models.Q(models.Q(('target_type__isnull', True), ('target_id__isnull', True)), models.Q(('target_type__isnull', False), ('target_id__isnull', False)), _connector='OR'), name='auditlog_auditevent_target_pair')],
            },
        ),
    ]
