/* Optional development check; no browser dependency is shipped to end users. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const base=process.env.PROTOTYPE_URL||'http://127.0.0.1:8765';
const out=process.env.QA_OUTPUT||'/tmp/secure-testing-ui-qa';fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})}),page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[],external=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('data:'))external.push(r.url());});
 const click=async(name)=>{await page.getByRole('button',{name,exact:true}).click();await page.waitForTimeout(350);};
 const launch=async(n)=>{await page.goto(base+'/preview.html');await page.locator(`[data-page="${n}"]`).click();await page.waitForURL('**/app.html#**');await page.evaluate(()=>document.fonts.ready);};
 const nav=async(route)=>{await page.evaluate(r=>location.hash=r,route);await page.waitForTimeout(70);};
 const checkTitle=async(s)=>assert.equal(await page.getByRole('heading',{level:1}).textContent(),s);
 const results=[];
 for(let n=1;n<=24;n++){
  await launch(n);await page.screenshot({path:path.join(out,`screen-${String(n).padStart(2,'0')}.png`),fullPage:true});
  const layout=await page.evaluate(()=>({width:document.documentElement.scrollWidth,font:document.fonts.check('14px Inter'),h1:document.querySelector('h1')?.textContent,overflow:[...document.querySelectorAll('button,.badge,input,select,.card')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).map(e=>e.className)}));
 assert.equal(layout.width,1440,`page ${n} horizontal overflow`);assert(layout.font,`page ${n} Inter not loaded`);assert.equal(layout.overflow.length,0,`page ${n} controls outside viewport`);results.push({page:n,...layout});
 }
 // Unsaved answer guard covers completion and question navigation; saved answers remain recoverable.
 await launch(15);await page.getByRole('radio').nth(1).check();assert(await page.getByText('Изменения не сохранены',{exact:true}).count());await page.getByRole('link',{name:'Завершить',exact:true}).click();assert(await page.getByRole('dialog').getByRole('heading',{name:'Уйти без сохранения?',exact:true}).count());await page.getByRole('dialog').getByRole('button',{name:'Отмена',exact:true}).click();assert(await page.getByRole('radio').nth(1).isChecked());
 await page.getByRole('link',{name:'Следующий вопрос →',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Уйти без сохранения',exact:true}).click();await page.getByText('Вопрос 2 из 3',{exact:true}).waitFor();await page.getByRole('link',{name:'← Предыдущий вопрос',exact:true}).click();await page.getByText('Вопрос 1 из 3',{exact:true}).waitFor();assert(await page.getByRole('radio').nth(0).isChecked());assert.equal(await page.getByRole('radio').nth(1).isChecked(),false);
 await page.getByRole('radio').nth(1).check();await click('Сохранить ответ');await page.getByRole('link',{name:'Следующий вопрос →',exact:true}).click();await page.getByText('Вопрос 2 из 3',{exact:true}).waitFor();await page.getByRole('link',{name:'← Предыдущий вопрос',exact:true}).click();await page.getByText('Вопрос 1 из 3',{exact:true}).waitFor();assert(await page.getByRole('radio').nth(1).isChecked());
 await page.getByRole('radio').nth(0).check();await page.evaluate(()=>{location.hash='student/tests';});await page.locator('dialog[open]').getByRole('button',{name:'Отмена',exact:true}).click();await checkTitle('Прохождение теста');assert(await page.getByRole('radio').nth(0).isChecked());await page.evaluate(()=>{location.hash='student/tests';});await page.locator('dialog[open]').getByRole('button',{name:'Уйти без сохранения',exact:true}).click();await page.getByRole('heading',{level:1,name:'Доступные тесты',exact:true}).waitFor();
 // Teacher form editing, blank option correction, readiness, activation, assignment and closure.
 await launch(6);assert.equal(await page.getByRole('textbox',{name:'Текст варианта 3',exact:true}).inputValue(),'');
 await page.getByRole('textbox',{name:'Текст варианта 3',exact:true}).fill('Хранение паролей в браузере');await click('Сохранить вопрос');await checkTitle('Основы информационной безопасности');assert(await page.getByRole('button',{name:'Активировать',exact:true}).isDisabled());
 await nav('teacher/question/10/102');await page.getByRole('radio',{name:'Вариант 1 правильный'}).check();await click('Сохранить вопрос');await page.getByRole('link',{name:'Активировать',exact:true}).click();await click('Активировать тест');assert(await page.getByText('Активен',{exact:true}).count());
 await nav('teacher/edit/10');await checkTitle('Действие невозможно');await nav('teacher/assignments/10');await page.locator('select[name=student_id]').selectOption('15');await click('Назначить');assert((await page.locator('.form-error').textContent()).includes('409'));
 await nav('teacher/test/10');await click('Закрыть тест');await page.getByRole('dialog').getByRole('button',{name:'Отмена'}).click();assert(await page.getByText('Активен',{exact:true}).count());await click('Закрыть тест');await page.getByRole('dialog').getByRole('button',{name:'Закрыть тест'}).click();await page.waitForTimeout(350);assert(await page.getByText('Закрыт',{exact:true}).count());await nav('teacher/assignments/10');assert.equal(await page.getByRole('button',{name:'Назначить',exact:true}).count(),0);
 // New test and question; position validation and literal text rendering.
 await launch(4);await page.locator('input[name=title]').fill('<b>Новый тест</b>');await click('Создать черновик');await checkTitle('<b>Новый тест</b>');assert.equal(await page.locator('h1 b').count(),0);await page.getByRole('link',{name:'Добавить вопрос',exact:true}).click();await page.locator('input[name=text]').fill('Вопрос');await page.getByRole('textbox',{name:'Текст варианта 1',exact:true}).fill('Один');await page.getByRole('textbox',{name:'Текст варианта 2',exact:true}).fill('Два');await page.getByRole('radio',{name:'Вариант 1 правильный'}).check();await click('Сохранить вопрос');assert(await page.getByRole('link',{name:'Активировать',exact:true}).count());await page.getByRole('link',{name:'Перейти',exact:true}).click();await page.locator('select[name=student_id]').selectOption('15');await click('Назначить');assert(await page.getByText('Создано',{exact:true}).count());
 // Saving and changing own answer, refresh recovery, completion with unanswered questions.
 await launch(15);await page.getByRole('radio').nth(1).check();await click('Сохранить ответ');await page.reload();assert(await page.getByRole('radio').nth(1).isChecked());await page.getByRole('radio').nth(0).check();await click('Сохранить ответ');await page.getByRole('link',{name:'Завершить',exact:true}).click();await page.getByRole('heading',{name:'Подтверждение завершения',exact:true}).waitFor();assert(await page.getByText('Без ответа: 2',{exact:true}).count());await click('Завершить попытку');await checkTitle('Результат попытки');assert(await page.getByText('33.33%',{exact:true}).count());assert.equal(await page.getByText('Что обеспечивает протокол HTTPS?',{exact:true}).count(),0);await nav('student/attempt/102');await checkTitle('Действие невозможно');await nav('student/test/40');assert(await page.getByText('Лимит попыток исчерпан.',{exact:true}).count());
 // Start once, resume, no DRAFT or foreign objects, same 404 message.
 await launch(14);await click('Начать попытку');await page.reload();await checkTitle('Прохождение теста');await nav('student/test/40');assert.equal(await page.getByRole('button',{name:'Начать попытку',exact:true}).count(),0);assert(await page.getByRole('link',{name:'Продолжить попытку',exact:true}).count());
 // A CLOSED test shows the ongoing attempt and completed-attempt history together.
 await click('Выйти');await page.locator('input[name=username]').fill('teacher2');await page.locator('input[name=password]').fill('demo1234');await click('Войти');await nav('teacher/test/40');await click('Закрыть тест');await page.getByRole('dialog').getByRole('button',{name:'Закрыть тест',exact:true}).click();await page.waitForTimeout(350);await click('Выйти');await page.locator('input[name=username]').fill('student1');await page.locator('input[name=password]').fill('demo1234');await click('Войти');await nav('student/test/40');assert(await page.getByRole('link',{name:'Продолжить попытку',exact:true}).count());assert.equal(await page.getByRole('link',{name:'Посмотреть результат',exact:true}).count(),1);
 await nav('student/test/10');await checkTitle('Страница не найдена');const missing1=await page.locator('main').innerText();await nav('student/test/99999');assert.equal(await page.locator('main').innerText(),missing1);await nav('admin/users');await checkTitle('Доступ запрещен');
 // Existing attempt remains usable after a teacher closes its test across sessions.
 await page.goto(base+'/preview.html');await page.locator('[data-role=TEACHER]').click();await nav('teacher/test/20');await click('Закрыть тест');await page.getByRole('dialog').getByRole('button',{name:'Закрыть тест'}).click();await page.waitForTimeout(350);await page.goto(base+'/preview.html');await page.locator('[data-role=STUDENT]').click();await nav('student/test/20');await page.getByRole('link',{name:'Продолжить попытку'}).click();await page.getByRole('radio').first().check();await click('Сохранить ответ');await page.getByRole('link',{name:'Завершить',exact:true}).click();await click('Завершить попытку');await checkTitle('Результат попытки');
 // Admin self restrictions, role conflict, block confirmation, unblock and account creation.
 await launch(19);await nav('admin/user/1');assert.equal(await page.getByRole('button',{name:'Сохранить роль'}).count(),0);assert.equal(await page.getByRole('button',{name:'Заблокировать'}).count(),0);
 await nav('admin/user/16');await page.locator('select[name=role]').selectOption('STUDENT');await click('Сохранить роль');await checkTitle('Изменение роли: конфликт');assert.equal(await page.getByRole('link',{name:'Компьютерные сети'}).count(),0);
 await nav('admin/user/15');await click('Заблокировать');await page.getByRole('dialog').getByRole('button',{name:'Заблокировать'}).click();await page.waitForTimeout(350);assert(await page.getByText('Заблокирован',{exact:true}).count());await click('Разблокировать');await page.getByRole('dialog').getByRole('button',{name:'Разблокировать'}).click();await page.waitForTimeout(350);assert(await page.getByText('Активен',{exact:true}).count());
 await nav('admin/create');await page.locator('input[name=username]').fill('new_student');await page.locator('input[name=password]').fill('NotStored123!');await click('Создать пользователя');await checkTitle('Учетная запись new_student');assert.equal(await page.evaluate(()=>localStorage.getItem('secure-testing-prototype-v1').includes('NotStored123!')),false);
 await nav('admin/audit');assert(await page.getByRole('columnheader',{name:'Время (UTC)',exact:true}).count());assert(await page.getByText('Журнал доступен только ADMIN. Секреты и содержимое ответов студентов в него не включаются.',{exact:true}).count());
 await click('Выйти');await page.locator('input[name=username]').fill('student1');await page.locator('input[name=password]').fill('wrong');await click('Войти');assert((await page.locator('.form-error').innerText()).includes('Неверные учетные данные'));await page.locator('input[name=password]').fill('demo1234');await click('Войти');await checkTitle('Доступные тесты');
 // Every screen is checked for horizontal overflow at both required narrow widths.
 const responsive=[];for(const [width,height] of [[390,844],[900,900]]){const checked=[];await page.setViewportSize({width,height});for(let n=1;n<=24;n++){await launch(n);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width,`page ${n} horizontal overflow at ${width}px`);checked.push(n);}responsive.push({viewport:`${width}x${height}`,screens:checked,overflow:[]});}
 await page.setViewportSize({width:390,height:844});await launch(13);await page.keyboard.press('Tab');assert(await page.evaluate(()=>document.activeElement!==document.body));
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({viewport:'1440x900',screens:results,responsive,scenarios:'passed',consoleErrors:errors,externalRequests:external,keyboardFocus:'390x844 passed'},null,2));console.log('PASS: 24 desktop screens; teacher/student/admin flows; unsaved-answer guard; CLOSED history; UTC label; all 24 screens at 390px and 900px; no external requests.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
