/* Standalone demonstration only. No backend, real authentication or security. */
(() => {
'use strict';
const KEY='secure-testing-prototype-v1', ACTOR=KEY+'-actor';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const roleNames={TEACHER:'Преподаватель',STUDENT:'Студент',ADMIN:'Администратор'};
const stateNames={DRAFT:'Черновик',ACTIVE:'Активен',CLOSED:'Закрыт'};
const now=()=>new Date().toISOString();
function seed(){
 const question=(id,test,position,text,options,correct=0)=>({id,test_id:test,position,text,options:options.map((text,i)=>({id:id*10+i+1,text,position:i+1,is_correct:i===correct}))});
 const q1=(id,t)=>question(id,t,1,'Что обеспечивает протокол HTTPS?',['Шифрование соединения','Защиту от всех вирусов','Хранение паролей в браузере']);
 const q2=(id,t)=>question(id,t,2,'Для чего нужен CSRF-токен?',['Для проверки подлинности запроса','Для сжатия изображений']);
 const q3=(id,t)=>question(id,t,3,'Какое действие помогает защитить учетную запись?',['Использовать надежный пароль','Передавать пароль другим']);
 return {users:[{id:1,username:'admin1',role:'ADMIN',is_active:true},{id:15,username:'student1',role:'STUDENT',is_active:true},{id:16,username:'teacher1',role:'TEACHER',is_active:true},{id:17,username:'student2',role:'STUDENT',is_active:false},{id:48,username:'student3',role:'STUDENT',is_active:true},{id:99,username:'teacher2',role:'TEACHER',is_active:true}],
 tests:[{id:10,owner_id:16,title:'Основы информационной безопасности',status:'DRAFT',max_attempts:2},{id:20,owner_id:16,title:'Компьютерные сети',status:'ACTIVE',max_attempts:1},{id:30,owner_id:16,title:'Основы программирования',status:'CLOSED',max_attempts:3},{id:40,owner_id:99,title:'Основы информационной безопасности',status:'ACTIVE',max_attempts:2},{id:50,owner_id:99,title:'Компьютерные сети',status:'CLOSED',max_attempts:2}],
 questions:[question(101,10,1,'Что обеспечивает протокол HTTPS?',['Шифрование соединения','Защиту от всех вирусов','']),question(102,10,2,'Для чего нужен CSRF-токен?',['Для проверки подлинности запроса','Для сжатия изображений'],-1),question(201,20,1,'Что такое IP-адрес?',['Уникальный адрес сетевого интерфейса','Название браузера']),question(202,20,2,'Для чего используется DNS?',['Для преобразования доменных имен в адреса','Для хранения паролей']),q1(301,30),q1(401,40),q2(402,40),q3(403,40),q1(501,50),q2(502,50)],
 assignments:[{id:71,test_id:10,student_id:15},{id:72,test_id:10,student_id:48},{id:73,test_id:20,student_id:15},{id:74,test_id:30,student_id:15},{id:75,test_id:40,student_id:15},{id:76,test_id:50,student_id:15},{id:77,test_id:20,student_id:48}],
 attempts:[{id:101,assignment_id:75,started_at:'2026-09-22T12:00:00Z',completed_at:'2026-09-22T12:10:00Z'},{id:109,assignment_id:76,started_at:'2026-09-23T12:00:00Z',completed_at:null},{id:110,assignment_id:73,started_at:'2026-09-23T12:00:00Z',completed_at:null},{id:111,assignment_id:77,started_at:'2026-09-22T12:00:00Z',completed_at:'2026-09-22T12:10:00Z'}],answers:[],results:[{id:91,attempt_id:101,score_points:2,correct_percentage:'66.67'},{id:92,attempt_id:111,score_points:1,correct_percentage:'50.00'}],events:[{id:1,occurred_at:'2026-09-23T18:40:00Z',category:'AUTH',event_type:'LOGIN',result:'SUCCESS',actor_id:15},{id:2,occurred_at:'2026-09-23T18:38:00Z',category:'ACCESS',event_type:'ROLE_DENIED',result:'DENIED',actor_id:16},{id:3,occurred_at:'2026-09-23T18:25:00Z',category:'ADMIN',event_type:'USER_CREATED',result:'SUCCESS',actor_id:1}],invalidated:{}};
}
let db;function read(){try{db=JSON.parse(localStorage.getItem(KEY))||seed();}catch{db=seed();}return db;}function save(){localStorage.setItem(KEY,JSON.stringify(db));}read();
const idFor=arr=>Math.max(0,...arr.map(x=>x.id))+1;
function actor(){try{const s=JSON.parse(sessionStorage.getItem(ACTOR));const u=db.users.find(u=>u.id===s?.id);return u&&u.is_active&&s.issued>=(db.invalidated[u.id]||0)?u:null;}catch{return null;}}
function loginAs(id){sessionStorage.setItem(ACTOR,JSON.stringify({id,issued:Date.now()}));}
function fail(code,message){throw {code,message};}
function requireRole(role){const u=actor();if(!u||u.role!==role)fail(403);return u;}
function ownTest(id,role){const u=requireRole(role);const t=db.tests.find(t=>t.id===Number(id));if(!t||(role==='TEACHER'?t.owner_id!==u.id:!['ACTIVE','CLOSED'].includes(t.status)||!db.assignments.some(a=>a.test_id===t.id&&a.student_id===u.id)))fail(404);return t;}
function ownAttempt(id,ongoing=false){const u=requireRole('STUDENT');const a=db.attempts.find(a=>a.id===Number(id)),as=db.assignments.find(s=>s.id===a?.assignment_id);if(!a||as?.student_id!==u.id)fail(404);ownTest(as.test_id,'STUDENT');if(ongoing&&a.completed_at)fail(409);return a;}
function questions(t){return db.questions.filter(q=>q.test_id===t.id).sort((a,b)=>a.position-b.position);}
function ready(t){const qs=questions(t);return qs.length>0&&qs.every(q=>q.text.trim()&&q.options.length>=2&&q.options.every(o=>o.text.trim())&&q.options.filter(o=>o.is_correct).length===1);}
function history(t){const as=db.assignments.find(a=>a.test_id===t.id&&a.student_id===actor().id);return db.attempts.filter(a=>a.assignment_id===as.id).sort((a,b)=>b.id-a.id);}
const href=(route)=>'#'+route;
const link=(label,route,kind='secondary')=>`<a class="btn ${kind}" href="${href(route)}">${esc(label)}</a>`;
const button=(label,action,kind='',extra='')=>`<button class="btn ${kind}" type="button" data-action="${action}" ${extra}>${esc(label)}</button>`;
const badge=(label,kind='')=>`<span class="badge ${kind}">${esc(label)}</span>`;
const status=t=>badge(stateNames[t.status],t.status.toLowerCase());
const field=(label,name,value='',type='text',extra='',helper='')=>`<label class="field"><span>${esc(label)}</span><input name="${name}" type="${type}" value="${esc(value)}" ${extra}>${helper?`<small>${esc(helper)}</small>`:''}</label>`;
const formError='<div class="form-error" role="alert"></div>';
const form=(name,body,extra='')=>`<form data-form="${name}" ${extra}>${formError}${body}</form>`;
const table=(heads,rows,widths=[])=>`<div class="table-wrap"><table>${widths.length?`<colgroup>${widths.map(w=>`<col style="width:${w}%">`).join('')}</colgroup>`:''}<thead><tr>${heads.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${heads.length}" class="empty">Пока нет данных</td></tr>`}</tbody></table></div>`;
const home=u=>u?.role==='ADMIN'?'admin/users':u?.role==='TEACHER'?'teacher/tests':'student/tests';
function shell(title,sub,body,{crumb='',right='',role=null}={}){const u=actor(),r=role||u?.role||'TEACHER';document.title=title+' · Secure Testing';return `<header class="header"><a class="brand" href="${href(home(u))}"><span class="brand-mark">S</span><span><strong>Secure Testing</strong><small>Университетская система тестирования</small></span></a><div class="account"><b>${roleNames[r]}</b><button type="button" class="plain" data-action="logout">Выйти</button></div></header>${r!=='STUDENT'?`<nav class="sidebar" aria-label="Основная навигация">${(r==='TEACHER'?[['Мои тесты','teacher/tests']]:[['Пользователи','admin/users'],['Журнал событий','admin/audit']]).map(([l,p])=>`<a href="#${p}" class="${location.hash.includes(p.split('/')[1])||p==='admin/users'&&!location.hash.includes('audit')?'active':''}">${l}</a>`).join('')}</nav>`:''}<main id="main" class="main ${r==='STUDENT'?'student':''}" tabindex="-1">${crumb?`<div class="breadcrumb"><a href="#${home(u)}">${r==='ADMIN'?'Пользователи':'Мои тесты'}</a><span>/ ${esc(crumb)}</span></div>`:''}<div class="page-head"><div><h1>${esc(title)}</h1>${sub?`<p>${esc(sub)}</p>`:''}</div>${right}</div>${body}</main>`;}
let route=[],toastTimer;
function go(r){if(location.hash===href(r))render();else location.hash=r;}
function toast(s){$('#toast').textContent=s;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').textContent='',3500);}
function errorPage(code,message=''){const msgs={400:['Проверьте данные','Исправьте поля формы и повторите попытку.'],401:['Не удалось войти','Неверные учетные данные.'],403:['Доступ запрещен','Недостаточно полномочий или сессия недействительна.'],404:['Страница не найдена','Объект отсутствует или недоступен.'],409:['Действие невозможно','Обновите страницу: текущее состояние объекта изменилось.']};const [h,p]=msgs[code]||msgs[404];return shell(h,'',`<section class="card error-page">${badge(code,code===409?'warning':'danger')}<h2>${h}</h2><p>${esc(message||p)}</p><div class="actions">${link(actor()?'На главную':'Войти',actor()?home(actor()):'login')}</div></section>`);}
function loginView(){document.title='Вход · Secure Testing';return `<main id="main" class="login"><section class="login-brand"><div class="brand-mark">S</div><h1>Secure Testing</h1><p>Система онлайн-тестирования<br>для университета</p><small>Доступ предоставляется администратором.</small></section><section class="login-form-wrap"><div class="card login-card"><h1>Вход в систему</h1><p>Используйте предоставленные учетные данные</p>${form('login',field('Имя пользователя','username','','text','required autocomplete="username"')+field('Пароль','password','','password','required autocomplete="current-password"')+'<button class="btn" type="submit">Войти</button>')}</div></section></main>`;}
function teacherView(){const u=requireRole('TEACHER'),s=route[1],id=route[2];
 if(s==='tests'){const tests=db.tests.filter(t=>t.owner_id===u.id);return shell('Мои тесты','Создавайте тесты, назначайте студентам и просматривайте результаты',`<section class="card list-card"><h3>Тесты преподавателя</h3>${table(['Название','Статус','Попыток','Действие'],tests.map(t=>[esc(t.title),status(t),t.max_attempts,`<a href="#teacher/test/${t.id}">Открыть →</a>`]),[48,18,14,20])}<p class="list-note">Отображаются только собственные тесты текущего преподавателя.</p></section>`,{right:link('+ Создать тест','teacher/create','')});}
 if(s==='create'||s==='edit'){const t=s==='edit'?ownTest(id,'TEACHER'):null;if(t&&t.status!=='DRAFT')fail(409);return shell(t?'Параметры теста':'Новый тест','Сначала задайте название и число попыток.',`<div class="grid create"><section class="card form-card"><h3>Основные параметры</h3>${form('test',field('Название теста','title',t?.title||'','text','required maxlength="255"')+`<div class="narrow">${field('Максимальное число попыток','max_attempts',t?.max_attempts||2,'number','required min="1" step="1"','Общий лимит для каждого назначенного студента.')}</div><div class="actions"><button class="btn" type="submit">${t?'Сохранить параметры':'Создать черновик'}</button>${link('Отмена',t?'teacher/test/'+t.id:'teacher/tests','neutral')}</div>`,t?`data-id="${t.id}"`:'')}</section><aside class="card" style="align-self:start"><h3>После создания</h3><p>Добавьте минимум один вопрос,<br>2 варианта к каждому вопросу<br>и один правильный вариант.</p></aside></div>`,{crumb:t?'Параметры':'Создать'});}
 const t=ownTest(id,'TEACHER'),qs=questions(t);
 if(s==='test'){
  if(t.status==='DRAFT')return shell(t.title,'Настройте вопросы, варианты ответов и назначения.',`<section class="card"><div class="row"><div><h3>Параметры теста</h3><p>Название: ${esc(t.title)}</p><p>Максимум попыток: ${t.max_attempts}</p></div>${link('Изменить','teacher/edit/'+t.id)}</div></section><div class="grid draft"><section class="card"><div class="row"><h3>Вопросы</h3>${link('+ Вопрос','teacher/question/'+t.id+'/new','')}</div>${qs.length?qs.map(q=>`<div class="question-row"><div><b>${q.position}. ${esc(q.text)}</b><p class="${q.options.some(o=>!o.text.trim())||!q.options.some(o=>o.is_correct)?'error-text':'muted'}">${q.options.length} варианта · ${q.options.some(o=>!o.text.trim())?'заполните пустые варианты':q.options.some(o=>o.is_correct)?'правильный вариант задан':'правильный вариант не задан'}</p></div>${link('Изменить','teacher/question/'+t.id+'/'+q.id,'neutral')}</div>`).join(''):'<div class="empty">Вопросов пока нет</div>'}</section><aside class="card"><h3>Активация</h3>${badge(ready(t)?'Готов к активации':'Не готов к активации',ready(t)?'success':'warning')}<p class="muted spaced">${ready(t)?'Проверьте содержание перед активацией.':'Нужно заполнить все вопросы и варианты, задать ровно один правильный вариант для каждого вопроса.'}</p><div class="spaced">${ready(t)?link('Активировать','teacher/activate/'+t.id,''):button('Активировать','noop','','disabled')}</div></aside></div><section class="card row"><div><h3>Назначения</h3><small>Назначения можно создавать уже в черновике.</small></div>${link('Перейти','teacher/assignments/'+t.id)}</section>`,{crumb:'Черновик',right:status(t)});
  if(t.status==='CLOSED')return shell(t.title,'Тест закрыт. Новые попытки и назначения запрещены.',`<section class="card"><h3>Содержание теста сохранено</h3><p class="muted">Название, лимит попыток, вопросы и правильные варианты доступны только для чтения.</p><div class="alert" style="margin-top:20px">Ранее начатые незавершенные попытки студентов могут быть продолжены и завершены.</div></section><section class="card"><h3>Доступные действия</h3><div class="actions">${link('Просмотреть вопросы','teacher/questions/'+t.id)}${link('Назначения','teacher/assignments/'+t.id,'neutral')}${link('Результаты','teacher/results/'+t.id,'')}</div></section>`,{crumb:'Закрытый тест',right:status(t)});
 }
 if(s==='test'||s==='questions')return shell(t.title,'Содержание теста доступно только для чтения.',`<section class="card"><h3>Параметры</h3><p>Название: ${esc(t.title)} &nbsp; Максимум попыток: ${t.max_attempts}</p></section><section class="card"><h3>Вопросы · только просмотр</h3>${qs.map(q=>`<div class="question-row"><div><b>${q.position}. ${esc(q.text)}</b>${q.options.map(o=>`<p class="${o.is_correct?'green':'muted'}">${esc(o.text)}${o.is_correct?' · правильный вариант':''}</p>`).join('')}</div></div>`).join('')}</section><section class="card row"><div class="actions">${link('Назначения','teacher/assignments/'+t.id)}${link('Результаты','teacher/results/'+t.id)}</div>${t.status==='ACTIVE'?button('Закрыть тест','close','danger',`data-id="${t.id}"`):link('Назад','teacher/test/'+t.id,'neutral')}</section>`,{crumb:t.status==='ACTIVE'?'Активный тест':'Вопросы',right:status(t)});
 if(s==='question'){if(t.status!=='DRAFT')fail(409);const q=route[3]==='new'?{id:null,text:'',position:Math.max(0,...qs.map(q=>q.position))+1,options:[{text:'',position:1},{text:'',position:2}]}:qs.find(q=>q.id===Number(route[3]));if(!q)fail(404);return shell('Редактирование вопроса','Редактирование доступно до активации теста.',`<section class="card form-card">${form('question',field('Текст вопроса','text',q.text,'text','required')+`<div class="narrow">${field('Позиция вопроса','position',q.position,'number','required min="1" step="1"')}</div><fieldset class="option-editor"><legend>Варианты ответа</legend><p class="muted">Выберите один правильный вариант.</p><div id="option-list">${q.options.map((o,i)=>optionEditor(o,i)).join('')}</div></fieldset><div class="actions"><button type="submit" class="btn">Сохранить вопрос</button>${button('+ Добавить вариант','add-option','secondary')}${link('Отмена','teacher/test/'+t.id,'neutral')}</div>`,`data-id="${t.id}" data-question="${q.id||''}"`)}</section>`,{crumb:'Черновик / Вопрос'});}
 if(s==='assignments'){const as=db.assignments.filter(a=>a.test_id===t.id),users=db.users.filter(u=>u.is_active&&u.role==='STUDENT');return shell('Назначения теста',t.status==='CLOSED'?'Просмотр ранее созданных назначений.':'Выберите студента и назначьте ему тест.',`${t.status!=='CLOSED'?`<section class="card"><h3>Назначить студенту</h3>${form('assign',`<div class="actions"><label class="field" style="flex:1;max-width:630px;margin-bottom:0"><span>Студент (username)</span><select name="student_id" required><option value="">Выберите студента</option>${users.map(u=>`<option value="${u.id}">${esc(u.username)} (ID ${u.id})</option>`).join('')}</select><small>При выборе отображаются только id и username.</small></label><button class="btn" type="submit" ${users.length?'':'disabled'}>Назначить</button></div>`,`data-id="${t.id}"`)}</section>`:''}<section class="card" style="min-height:337px"><h3>Созданные назначения</h3>${table(['ID назначения','ID студента','Состояние связи'],as.map(a=>[a.id,a.student_id,'Создано']))}<p class="list-note">Изменение уже созданной связи и удаление недоступны.</p></section>`,{crumb:stateNames[t.status]+' / Назначения',right:status(t)});}
 if(s==='activate'){if(t.status!=='DRAFT'||!ready(t))fail(409);return shell('Проверка перед активацией','После активации содержание теста нельзя изменить.',`<section class="card confirm-card">${badge('Готов к активации','success')}<h2 class="spaced">Проверка содержания пройдена</h2><div class="stack green"><p>✓ Минимум один вопрос</p><p>✓ Для каждого вопроса минимум два варианта</p><p>✓ Для каждого вопроса ровно один правильный вариант</p></div><div class="alert warning">После активации название, лимит попыток и содержание не редактируются.</div><div class="actions">${button('Активировать тест','activate','',`data-id="${t.id}"`)}${link('Вернуться','teacher/test/'+t.id,'neutral')}</div></section>`,{crumb:'Черновик / Активация'});}
 if(s==='results'){const rows=db.results.flatMap(r=>{const a=db.attempts.find(a=>a.id===r.attempt_id),as=db.assignments.find(as=>as.id===a?.assignment_id);return as?.test_id===t.id?[[r.id,as.student_id,r.score_points,r.correct_percentage+'%']]:[];});return shell('Результаты теста','Результаты прохождения ваших тестов.',`<section class="card" style="min-height:515px"><h3>Результаты прохождения</h3>${table(['ID результата','ID студента','Баллы','Правильных ответов'],rows)}</section>`,{crumb:t.title+' / Результаты'});}
 fail(404);
}
function optionEditor(o,i){return `<div class="option"><input type="radio" name="correct" value="${i}" ${o.is_correct?'checked':''} required aria-label="Вариант ${i+1} правильный"><input class="grow" type="text" name="option_text" value="${esc(o.text)}" placeholder="Введите текст варианта" required aria-label="Текст варианта ${i+1}"><input type="number" name="option_position" value="${o.position||i+1}" min="1" step="1" required aria-label="Позиция варианта ${i+1}"></div>`;}
function studentView(){const u=requireRole('STUDENT'),s=route[1],id=route[2];
 if(s==='tests'){const ts=db.tests.filter(t=>['ACTIVE','CLOSED'].includes(t.status)&&db.assignments.some(a=>a.test_id===t.id&&a.student_id===u.id));return shell('Доступные тесты','Тесты, которые назначил вам преподаватель.',ts.length?ts.map(t=>`<section class="card row student-test"><div><h2>${esc(t.title)}</h2><small>${history(t).some(a=>!a.completed_at)?'Незавершенная попытка':t.status==='CLOSED'?'Новые попытки недоступны':'Максимум попыток: '+t.max_attempts}</small></div><div class="right">${status(t)}${link('Открыть тест','student/test/'+t.id)}</div></section>`).join(''):'<section class="card empty">Вам пока не назначены тесты.</section>');}
 if(s==='test'){const t=ownTest(id,'STUDENT'),hs=history(t),ongoing=hs.find(a=>!a.completed_at);if(t.status==='CLOSED')return shell(t.title,'Закрытие теста не прерывает собственную ранее начатую попытку.',`<section class="card" style="min-height:352px"><h2>Тест закрыт</h2><p class="muted">Новые попытки недоступны.</p>${ongoing?`<div class="alert spaced"><h3>У вас есть незавершенная попытка #${ongoing.id}</h3><p>Вы можете продолжить ее и завершить тестирование.</p></div><div class="spaced">${link('Продолжить попытку','student/attempt/'+ongoing.id,'')}</div>`:attemptHistory(hs)}</section>`,{crumb:'Закрытый тест',right:status(t)});return shell(t.title,'Посмотрите условия и начните прохождение.',`<div class="grid detail"><section class="card" style="min-height:255px"><h2>Информация о тесте</h2><p>Статус: активен</p><p>Максимум попыток: ${t.max_attempts}</p><p>Использовано попыток: ${hs.length}</p><div style="margin-top:24px">${ongoing?link('Продолжить попытку','student/attempt/'+ongoing.id,''):hs.length<t.max_attempts?button('Начать попытку','start','',`data-id="${t.id}"`):`<div class="alert warning">Лимит попыток исчерпан.</div>`}</div></section><section class="card"><h2>Мои попытки</h2>${attemptHistory(hs)}</section></div>`,{crumb:'Информация о тесте',right:status(t)});}
 const a=ownAttempt(id,s!=='result'),as=db.assignments.find(as=>as.id===a.assignment_id),t=ownTest(as.test_id,'STUDENT');
 if(s==='result'){if(!a.completed_at)fail(409);const result=db.results.find(r=>r.attempt_id===a.id);if(!result)fail(409);return shell('Результат попытки','Вы завершили прохождение теста.',`<section class="card result-card">${badge('Завершена','success')}<h3 class="spaced">Тест: ${esc(t.title)}</h3><div class="metrics"><div class="metric"><p class="muted">Набрано баллов</p><strong>${result.score_points}</strong></div><div class="metric"><p class="muted">Правильных ответов</p><strong>${result.correct_percentage}%</strong></div></div></section><div style="margin-top:44px">${link('Вернуться к тестам','student/tests')}</div>`,{crumb:'Попытка #'+a.id+' / Результат'});}
 const qs=questions(t);
 if(s==='complete'){const answered=db.answers.filter(x=>x.attempt_id===a.id&&qs.some(q=>q.id===x.question_id)).length;return shell('Подтверждение завершения','Завершение попытки необратимо.',`<section class="card confirm-card"><h2>Завершить попытку?</h2><div class="stack"><p>Всего вопросов: ${qs.length}</p><p>С сохраненным ответом: ${answered}</p><p style="color:var(--orange)">Без ответа: ${qs.length-answered}</p></div><div class="alert warning"><p>Вопросы без ответа будут считаться неправильными.</p><p>После завершения ответы изменить невозможно.</p></div><div class="actions">${button('Завершить попытку','complete','',`data-id="${a.id}"`)}${link('Вернуться к вопросам','student/attempt/'+a.id,'neutral')}</div></section>`,{crumb:'Попытка #'+a.id+' / Завершение'});}
 if(s==='attempt'){const index=Number(route[3]||0);if(!Number.isInteger(index)||index<0||index>=qs.length)fail(404);const q=qs[index],answer=db.answers.find(x=>x.attempt_id===a.id&&x.question_id===q.id);return shell('Прохождение теста','Выберите один ответ и сохраните его перед переходом дальше.',`<section class="card attempt-card"><b class="blue">Вопрос ${index+1} из ${qs.length}</b><h2>${esc(q.text)}</h2>${form('answer',`<fieldset><legend class="sr-only" style="position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)">Выберите один вариант</legend>${q.options.map(o=>`<label class="option"><input type="radio" name="option" value="${o.id}" ${answer?.answer_option_id===o.id?'checked':''} required><span>${esc(o.text)}</span></label>`).join('')}</fieldset><div id="saved-state" style="margin-top:36px">${badge(answer?'Ответ сохранен':'Ответ не сохранен',answer?'success':'warning')}</div><div class="actions"><button type="submit" class="btn">Сохранить ответ</button>${index>0?link('← Предыдущий вопрос',`student/attempt/${a.id}/${index-1}`):''}${index<qs.length-1?link('Следующий вопрос →',`student/attempt/${a.id}/${index+1}`):link('К завершению','student/complete/'+a.id)}</div>`,`data-id="${a.id}" data-question="${q.id}"`)}</section><div class="row attempt-footer"><small>Завершить прохождение можно даже при наличии вопросов без ответа.</small>${link('Завершить','student/complete/'+a.id,'neutral')}</div>`,{crumb:'Попытка #'+a.id,right:badge('В процессе','blue')});}fail(404);
}
function attemptHistory(hs){return hs.length?`<div class="stack">${hs.map(a=>`<div><p>Попытка #${a.id} &nbsp; ${a.completed_at?'Завершена':'В процессе'}</p>${a.completed_at?`<a class="green" href="#student/result/${a.id}">Посмотреть результат</a>`:`<a href="#student/attempt/${a.id}">Продолжить</a>`}</div>`).join('')}</div>`:'<p class="muted">Вы еще не начинали прохождение.</p>';}
function adminView(){const u=requireRole('ADMIN'),s=route[1],id=route[2];
 if(s==='users')return shell('Пользователи','Создавайте учетные записи и управляйте доступом.',`<section class="card list-card"><h3>Учетные записи</h3>${table(['ID','Имя пользователя','Роль','Статус','Действие'],db.users.map(x=>[x.id,esc(x.username),x.role,badge(x.is_active?'Активен':'Заблокирован',x.is_active?'active':'danger'),x.id===u.id?'Своя запись':`<a href="#admin/user/${x.id}">Открыть →</a>`]),[8,26,20,23,23])}</section>`,{right:link('+ Создать','admin/create','')});
 if(s==='create')return shell('Новая учетная запись','Укажите данные для входа и роль пользователя.',`<section class="card form-card" style="max-width:832px;min-height:518px">${form('user-create',field('Имя пользователя','username','','text','required maxlength="150" autocomplete="off"')+field('Пароль','password','','password','required autocomplete="new-password"','Используйте надежный пароль.')+`<fieldset><legend>Роль пользователя</legend><div class="role-options">${['STUDENT','TEACHER','ADMIN'].map((r,i)=>`<label class="option"><input type="radio" name="role" value="${r}" ${i===0?'checked':''}>${r}</label>`).join('')}</div></fieldset><div class="actions"><button class="btn" type="submit">Создать пользователя</button>${link('Отмена','admin/users','neutral')}</div>`)}</section>`,{crumb:'Создание'});
 if(s==='audit')return shell('Журнал событий','История входов, изменений доступа и административных действий.',`<section class="card" style="min-height:602px"><h3>События системы</h3>${table(['Время','Категория','Тип','Результат','Actor ID'],db.events.slice().sort((a,b)=>b.occurred_at.localeCompare(a.occurred_at)).map(e=>[esc(e.occurred_at.slice(0,16).replace('T',' ')),esc(e.category),esc(e.event_type),esc(e.result),esc(e.actor_id)]),[20,18,26,18,18])}<div class="alert" style="margin-top:72px">Журнал доступен только ADMIN. Секреты и содержимое ответов студентов в него не включаются.</div></section>`);
 const target=db.users.find(x=>x.id===Number(id));if(!target)fail(404);
 if(s==='conflict')return shell('Изменение роли: конфликт','Роль пользователя не изменена.',`<section class="card error-page">${badge('409 Conflict','danger')}<h2>Изменение роли невозможно</h2><p>У преподавателя есть активные тесты. Сначала необходимо закрыть их.</p><div class="actions">${link('Вернуться к пользователю','admin/user/'+target.id)}</div></section>`,{crumb:target.username});
 if(s==='user')return shell('Учетная запись '+target.username,'Измените роль или доступ пользователя к системе.',`<section class="card row"><div><p>ID: ${target.id}</p><p><b>Username: ${esc(target.username)}</b></p><p>Текущая роль: ${target.role}</p></div>${badge(target.is_active?'Активен':'Заблокирован',target.is_active?'active':'danger')}</section>${target.id===u.id?'<section class="card"><p>Это ваша учетная запись. Изменение собственной роли и блокировка недоступны.</p></section>':`<div class="grid two"><section class="card"><h3>Изменение роли</h3>${form('role',`<label class="field"><span>Новая роль</span><select name="role">${['STUDENT','TEACHER','ADMIN'].map(r=>`<option ${target.role===r?'selected':''}>${r}</option>`).join('')}</select></label><button class="btn" type="submit">Сохранить роль</button>`,`data-id="${target.id}"`)}</section><section class="card"><h3>Управление доступом</h3><p class="muted">Блокировка прекращает защищенный доступ.</p><p class="muted">После разблокировки нужен новый вход.</p><div class="spaced">${button(target.is_active?'Заблокировать':'Разблокировать','block',target.is_active?'danger':'secondary',`data-id="${target.id}"`)}</div></section></div>`}`,{crumb:target.username});fail(404);
}
function kit(){requireRole('TEACHER');return shell('UI Kit и состояния','Общие визуальные элементы, используемые всеми тремя ролями',`<section class="card" style="min-height:179px"><h3>Кнопки</h3><div class="actions">${button('Основное действие','sample')}${button('Вторичное','sample','secondary')}${button('Нейтральное','sample','neutral')}${button('Заблокировано','noop','','disabled')}${button('Закрыть тест','sample','danger')}${button('Загрузка','sample-load','secondary')}</div></section><div class="grid two"><section class="card"><h3>Поля и ошибки</h3>${field('Название теста','sample','Основы информатики','text','aria-describedby="sample-error"')}<p class="error-text" id="sample-error">Ошибка: поле обязательно для заполнения</p></section><section class="card"><h3>Статусы</h3><div class="actions">${badge('Черновик')}${badge('Активен','active')}${badge('Закрыт')}${badge('Ошибка','danger')}</div><p class="muted spaced">Состояния: default / hover / focus / disabled / loading / error</p></section></div><section class="card"><h3>Сообщения</h3><div class="grid two"><div class="alert success">Сохранено. Изменения применены.</div><div class="alert danger">Действие невозможно: обновите состояние.</div></div></section>`);}
function errors(){if(!actor())fail(403);return shell('Системные состояния','Нейтральные ответы и сообщения об ошибках без раскрытия закрытых данных',`<div class="grid two">${[[403,'Доступ запрещен','Недостаточно полномочий или сессия недействительна.','danger'],[404,'Страница не найдена','Объект отсутствует или недоступен.',''],[409,'Действие невозможно','Обновите страницу: текущее состояние объекта изменилось.','warning'],[400,'Проверьте данные','Исправьте поля формы и повторите попытку.','blue']].map(([c,h,p,k])=>`<section class="card error-card">${badge(c,k)}<h2>${h}</h2><small>${p}</small><div>${link('Назад',home(actor()),'neutral')}</div></section>`).join('')}</div>`);}
function render(){read();route=location.hash.slice(1).split('/');if(!route[0])route=['login'];try{const view=route[0]==='login'?loginView():route[0]==='teacher'?teacherView():route[0]==='student'?studentView():route[0]==='admin'?adminView():route[0]==='kit'?kit():route[0]==='errors'?errors():route[0]==='error'?errorPage(Number(route[1])):errorPage(404);$('#app').innerHTML=view;window.scrollTo(0,0);}catch(e){if(!e.code){console.error(e);$('#app').innerHTML=errorPage(400,'Не удалось отобразить демонстрационные данные. Вернитесь в preview.html и сбросьте пример.');}else $('#app').innerHTML=errorPage(e.code,e.message);}}
function event(category,type,result='SUCCESS'){db.events.push({id:idFor(db.events),occurred_at:now(),category,event_type:type,result,actor_id:actor()?.id??null});}
async function busy(el,fn){if(el?.disabled)return;const label=el?.textContent;if(el){el.disabled=true;el.setAttribute('aria-busy','true');el.textContent='Подождите...';}await new Promise(r=>setTimeout(r,250));try{read();await fn();}finally{if(el?.isConnected){el.disabled=false;el.removeAttribute('aria-busy');el.textContent=label;}}}
function confirm(title,message,yes,callback){const d=$('#confirm');d.innerHTML=`<h2 id="dialog-title">${esc(title)}</h2><p>${esc(message)}</p><div class="actions"><button type="button" class="btn neutral" data-cancel>Отмена</button><button type="button" class="btn danger" data-yes>${esc(yes)}</button></div>`;d.showModal();$('[data-cancel]',d).onclick=()=>d.close();$('[data-yes]',d).onclick=async e=>{try{await busy(e.target,callback);d.close();}catch(err){d.close();$('#app').innerHTML=errorPage(err.code||400,err.message);}};}
function positive(v){const n=Number(v);if(!Number.isSafeInteger(n)||n<1)fail(400,'Введите целое число не меньше 1.');return n;}
function draft(id){const t=ownTest(id,'TEACHER');if(t.status!=='DRAFT')fail(409);return t;}
function addAttempt(t){const hs=history(t);if(t.status!=='ACTIVE'||hs.some(a=>!a.completed_at)||hs.length>=t.max_attempts)fail(409);const as=db.assignments.find(a=>a.test_id===t.id&&a.student_id===actor().id);const a={id:idFor(db.attempts),assignment_id:as.id,started_at:now(),completed_at:null};db.attempts.push(a);return a;}
function commitAction(fn){try{fn();}catch(e){$('#app').innerHTML=errorPage(e.code||400,e.message);}}
if($('#app')){
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const action=b.dataset.action,id=Number(b.dataset.id);if(action==='logout'){sessionStorage.removeItem(ACTOR);go('login');return;}if(action==='add-option'){const list=$('#option-list');list.insertAdjacentHTML('beforeend',optionEditor({text:''},list.children.length));$('input[type=text]',list.lastElementChild).focus();return;}if(action==='sample'){toast('Демонстрация состояния кнопки');return;}if(action==='sample-load'){await busy(b,()=>toast('Загрузка завершена'));return;}if(action==='noop')return;
 try{read();if(action==='close'){const t=ownTest(id,'TEACHER');if(t.status!=='ACTIVE')fail(409);confirm('Закрыть тест?','Новые попытки и назначения станут недоступны. Уже начатые попытки можно будет завершить.','Закрыть тест',()=>{const t=ownTest(id,'TEACHER');if(t.status!=='ACTIVE')fail(409);t.status='CLOSED';event('TEST','TEST_CLOSED');save();render();toast('Тест закрыт');});return;}
 if(action==='block'){const u=requireRole('ADMIN'),target=db.users.find(x=>x.id===id);if(!target)fail(404);if(target.id===u.id)fail(403);const was=target.is_active;confirm(was?'Заблокировать пользователя?':'Разблокировать пользователя?',was?'Пользователь потеряет доступ к системе.':'После разблокировки пользователю потребуется войти заново.',was?'Заблокировать':'Разблокировать',()=>{requireRole('ADMIN');const t=db.users.find(x=>x.id===id);if(t.is_active!==was)fail(409);t.is_active=!was;if(was)db.invalidated[id]=Date.now();event('ADMIN',was?'USER_BLOCKED':'USER_UNBLOCKED');save();render();toast(was?'Пользователь заблокирован':'Пользователь разблокирован');});return;}
 await busy(b,()=>{if(action==='activate'){const t=draft(id);if(!ready(t))fail(409);t.status='ACTIVE';event('TEST','TEST_ACTIVATED');save();go('teacher/test/'+id);}
 else if(action==='start'){const t=ownTest(id,'STUDENT'),a=addAttempt(t);event('ATTEMPT','ATTEMPT_STARTED');save();go('student/attempt/'+a.id);}
 else if(action==='complete'){const a=ownAttempt(id,true),as=db.assignments.find(x=>x.id===a.assignment_id),t=ownTest(as.test_id,'STUDENT'),qs=questions(t);let score=0;for(const q of qs){const ans=db.answers.find(x=>x.attempt_id===a.id&&x.question_id===q.id);if(q.options.some(o=>o.id===ans?.answer_option_id&&o.is_correct))score++;}if(db.results.some(r=>r.attempt_id===a.id))fail(409);a.completed_at=now();db.results.push({id:idFor(db.results),attempt_id:a.id,score_points:score,correct_percentage:(score/qs.length*100).toFixed(2)});event('ATTEMPT','ATTEMPT_COMPLETED');save();go('student/result/'+a.id);}});
 }catch(err){$('#app').innerHTML=errorPage(err.code||400,err.message);}
 });
 document.addEventListener('change',e=>{if(e.target.name==='option'){const n=$('#saved-state');if(n)n.innerHTML=badge('Изменения не сохранены','warning');}});
 document.addEventListener('submit',async e=>{const f=e.target.closest('[data-form]');if(!f)return;e.preventDefault();const data=new FormData(f),kind=f.dataset.form,submit=$('button[type=submit]',f);$('.form-error',f).textContent='';
 try{await busy(submit,()=>{
 if(kind==='login'){const user=db.users.find(x=>x.username===String(data.get('username')).trim()&&x.is_active);if(!user||data.get('password')!=='demo1234')fail(401,'Неверные учетные данные.');loginAs(user.id);event('AUTH','LOGIN');save();go(home(user));return;}
 if(kind==='test'){const u=requireRole('TEACHER'),title=String(data.get('title')).trim(),max=positive(data.get('max_attempts'));if(!title||title.length>255)fail(400,'Укажите название длиной до 255 символов.');let t;if(f.dataset.id){t=draft(f.dataset.id);Object.assign(t,{title,max_attempts:max});}else{t={id:idFor(db.tests),owner_id:u.id,title,status:'DRAFT',max_attempts:max};db.tests.push(t);}event('TEST','TEST_SAVED');save();go('teacher/test/'+t.id);return;}
 if(kind==='question'){const t=draft(f.dataset.id),qs=questions(t),qid=Number(f.dataset.question),existing=qid?qs.find(q=>q.id===qid):null;if(qid&&!existing)fail(404);const text=String(data.get('text')).trim(),position=positive(data.get('position')),texts=data.getAll('option_text').map(x=>String(x).trim()),positions=data.getAll('option_position').map(positive),correct=Number(data.get('correct'));if(!text||texts.length<2||texts.some(x=>!x)||data.get('correct')===null||correct<0||correct>=texts.length)fail(400,'Заполните вопрос и все варианты, выберите один правильный ответ.');if(qs.some(q=>q.id!==qid&&q.position===position)||new Set(positions).size!==positions.length)fail(400,'Позиции должны быть уникальными.');const id=existing?.id||idFor(db.questions);let next=Math.max(0,...db.questions.flatMap(q=>q.options.map(o=>o.id)))+1;const options=texts.map((text,i)=>({id:existing?.options[i]?.id||next++,text,position:positions[i],is_correct:i===correct})).sort((a,b)=>a.position-b.position);if(existing)Object.assign(existing,{text,position,options});else db.questions.push({id,test_id:t.id,text,position,options});event('TEST','QUESTION_SAVED');save();go('teacher/test/'+t.id);return;}
 if(kind==='assign'){const t=ownTest(f.dataset.id,'TEACHER');if(t.status==='CLOSED')fail(409);const student=db.users.find(u=>u.id===Number(data.get('student_id'))&&u.role==='STUDENT'&&u.is_active);if(!student)fail(400,'Некорректные данные.');if(db.assignments.some(a=>a.test_id===t.id&&a.student_id===student.id))fail(409,'Это назначение уже существует.');db.assignments.push({id:idFor(db.assignments),test_id:t.id,student_id:student.id});event('TEST','TEST_ASSIGNED');save();render();toast('Тест назначен');return;}
 if(kind==='answer'){const a=ownAttempt(f.dataset.id,true),as=db.assignments.find(x=>x.id===a.assignment_id),q=questions(ownTest(as.test_id,'STUDENT')).find(q=>q.id===Number(f.dataset.question)),option=q?.options.find(o=>o.id===Number(data.get('option')));if(!q||!option)fail(400,'Некорректные данные.');const ans=db.answers.find(x=>x.attempt_id===a.id&&x.question_id===q.id);if(ans)ans.answer_option_id=option.id;else db.answers.push({id:idFor(db.answers),attempt_id:a.id,question_id:q.id,answer_option_id:option.id});save();$('#saved-state').innerHTML=badge('Ответ сохранен','success');toast('Ответ сохранен');return;}
 const u=requireRole('ADMIN');
 if(kind==='user-create'){const username=String(data.get('username')).trim(),role=data.get('role'),password=String(data.get('password'));if(!username||username.length>150||!/^[-\w.@+\u0400-\u04ff]+$/u.test(username)||!roleNames[role]||!password)fail(400,'Проверьте имя пользователя, пароль и роль.');if(db.users.some(u=>u.username===username))fail(409,'Пользователь с таким именем уже существует.');const target={id:idFor(db.users),username,role,is_active:true};db.users.push(target);event('ADMIN','USER_CREATED');save();go('admin/user/'+target.id);return;}
 if(kind==='role'){const target=db.users.find(x=>x.id===Number(f.dataset.id));if(!target)fail(404);if(target.id===u.id)fail(403);const role=data.get('role');if(!roleNames[role])fail(400);if(target.role==='TEACHER'&&role!=='TEACHER'&&db.tests.some(t=>t.owner_id===target.id&&t.status==='ACTIVE')){go('admin/conflict/'+target.id);return;}target.role=role;event('ADMIN','ROLE_CHANGED');save();render();toast('Роль сохранена');return;}
 });}catch(err){const n=$('.form-error',f);if(n){n.textContent=(err.code||400)+': '+(err.message||({403:'Доступ запрещен.',404:'Объект отсутствует или недоступен.',409:'Действие невозможно: состояние изменилось.'}[err.code]||'Проверьте данные.'));n.tabIndex=-1;n.focus();}else $('#app').innerHTML=errorPage(err.code||400,err.message);}
 });
 window.addEventListener('hashchange',render);window.addEventListener('storage',e=>{if(e.key===KEY)render();});render();
}
// Preview-only launcher. This module's local fixtures are not a security boundary.
window.Prototype={reset(){db=seed();save();sessionStorage.removeItem(ACTOR);},launch(role,path,fixture=''){
 read();if(fixture){db=seed();if(['ready'].includes(fixture)){db.questions.find(q=>q.id===101).options[2].text='Хранение паролей в браузере';db.questions.find(q=>q.id===102).options[0].is_correct=true;}
 if(['attempt','complete','result'].includes(fixture)){const a={id:102,assignment_id:75,started_at:now(),completed_at:fixture==='result'?now():null};db.attempts.push(a);db.answers.push({id:1,attempt_id:102,question_id:401,answer_option_id:4011});if(fixture!=='attempt')db.answers.push({id:2,attempt_id:102,question_id:402,answer_option_id:4021});if(fixture==='result')db.results.push({id:93,attempt_id:102,score_points:2,correct_percentage:'66.67'});}
 save();}loginAs({TEACHER:16,STUDENT:15,ADMIN:1}[role]);location.href='app.html#'+path;
}};
})();
